//ADD_TODO;
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCEEDED = "ADD_TODO_SUCCEEDED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const LIST_TODO = "LIST_TODO";
//FIN ADD_TODO;
