//ADD_TODO;
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCEEDED = "ADD_TODO_SUCCEEDED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const LIST_TODO = "LIST_TODO";

/* OWNERS LIST */
export const OWNERS_LIST_GET_LIST = "OWNERS_LIST_GET_LIST";
export const OWNERS_LIST_GET_LIST_SUCCESS = "OWNERS_LIST_GET_LIST_SUCCESS";
export const OWNERS_LIST_GET_LIST_ERROR = "OWNERS_LIST_GET_LIST_ERROR";



